### ISSUE TITLE
possibly retry codesign. possibly make signing synchronous. possibly detect other unlock issues

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker-scripts#2]
We hit a couple `codesign` issues on a single host (6).

This was while we were codesigning two `plugin-container.app`'s concurrently.

[full log](https://taskcluster-artifacts.net/IgqHH-x8T3a_oX_OWr0LRA/0/public/logs/live_backing.log)

<details><summary>partial log</summary>

```
2019-06-28 00:12:58,497 - scriptworker_client.utils - INFO - Running ['codesign', '-s', '43AQ936H96', '-fv', '--keychain', '/builds/scriptworker/nightly-signing.keychain', '--requirement', '=designated => ( (anchor apple generic and certificate leaf[field.1.2.840.113635.100.6.1.9] ) or (anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] and certificate leaf[field.1.2.840.113635.100.6.1.13] and certificate leaf[subject.OU] = "43AQ936H96"))', '-o', 'runtime', '--entitlements', '/builds/scriptworker/work/browser.entitlements.txt', 'plugin-container.app'] in /builds/scriptworker/work/3/Firefox Nightly.app/Contents/MacOS ...
2019-06-28 00:12:58,513 - scriptworker_client.utils - INFO - plugin-container.app: errSecInternalComponent
2019-06-28 00:12:58,514 - scriptworker_client.utils - INFO - plugin-container.app: errSecInternalComponent
2019-06-28 00:12:58,537 - scriptworker_client.utils - INFO - plugin-container.app: replacing existing signature
2019-06-28 00:12:58,562 - scriptworker_client.utils - INFO - plugin-container.app: errSecInternalComponent
2019-06-28 00:12:58,566 - scriptworker_client.utils - INFO - plugin-container.app: replacing existing signature
2019-06-28 00:12:58,591 - scriptworker_client.utils - INFO - plugin-container.app: errSecInternalComponent
2019-06-28 00:12:58,593 - scriptworker_client.client - ERROR - Failed to run async_main
Traceback (most recent call last):
  File "/builds/scriptworker/scriptworker-scripts/scriptworker_client/src/scriptworker_client/client.py", line 156, in _handle_asyncio_loop
    await async_main(config, task)
  File "/builds/scriptworker/scriptworker-scripts/iscript/src/iscript/script.py", line 47, in async_main
    await notarize_behavior(config, task)
  File "/builds/scriptworker/scriptworker-scripts/iscript/src/iscript/mac.py", line 1075, in notarize_behavior
    await sign_all_apps(config, key_config, entitlements_path, all_paths)
  File "/builds/scriptworker/scriptworker-scripts/iscript/src/iscript/mac.py", line 585, in sign_all_apps
    await raise_future_exceptions(futures)
  File "/builds/scriptworker/scriptworker-scripts/scriptworker_client/src/scriptworker_client/aio.py", line 55, in raise_future_exceptions
    raise exceptions[0]
  File "/builds/scriptworker/scriptworker-scripts/iscript/src/iscript/mac.py", line 209, in sign_app
    await sign_app(key_config, abs_dir, entitlements_path)
  File "/builds/scriptworker/scriptworker-scripts/iscript/src/iscript/mac.py", line 241, in sign_app
    output_log_on_exception=True,
  File "/builds/scriptworker/scriptworker-scripts/scriptworker_client/src/scriptworker_client/utils.py", line 230, in run_command
    "%s in %s exited %s!\n%s", log_cmd, cwd, exitcode, log_contents
iscript.exceptions.IScriptError: ('%s in %s exited %s!\n%s', ['codesign', '-s', '43AQ936H96', '-fv', '--keychain', '/builds/scriptworker/nightly-signing.keychain', '--requirement', '=designated => ( (anchor apple generic and certificate leaf[field.1.2.840.113635.100.6.1.9] ) or (anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] and certificate leaf[field.1.2.840.113635.100.6.1.13] and certificate leaf[subject.OU] = "43AQ936H96"))', '-o', 'runtime', '--entitlements', '/builds/scriptworker/work/browser.entitlements.txt', 'plugin-container.app'], '/builds/scriptworker/work/0/Firefox Nightly.app/Contents/MacOS', 1, 'plugin-container.app: replacing existing signature\nplugin-container.app: errSecInternalComponent\n')
exit code: 1
```

**Comment by escapewindow** [comment]
Possibly fixed by https://github.com/escapewindow/scriptworker-scripts/commit/7369d7a6811de28b8079be0294299422a4765741
